config/routes.rb
Rails.application.routes.draw do
  resources :stories do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'stories#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  mount Shrine::DownloadEndpoint => "/attachments"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story
  belongs_to :created_by, class_name: "User"
end

app/models/image_uploader.rb
require "image_processing/mini_magick"
class ImageUploader < Shrine
  # plugins and uploading logic
  include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions   # enable Shrine to handle a hash of files
  plugin :delete_raw # delete processed files after uploading

  process(:store) do |io, context|
    original = io.download

    size_800 = resize_to_limit!(original, 800, 800) { |cmd| cmd.auto_orient } # orient rotated images
    size_500 = resize_to_limit(size_800,  500, 500)
    size_300 = resize_to_limit(size_500,  300, 300)
    size_thumbnail = resize_to_limit(size_300, 64, 64)

    {original: io, large: size_800, medium: size_500, small: size_300, thumbnail: size_thumbnail}
  end
end

app/models/link_image_grabber.rb
class LinkImageGrabber
  def initialize(story)
    @story = story
  end

  def process
    if @story.image
      puts "failing"
      p @story.image
      return
    end

    # Use the open-uri method to suck down the contents of the link
    page_source = open(@story.link)
    puts "downloaded the src"
    # use nokogiri to parse the HTML we downloaded into an object we can ask questions of
    page_content = Nokogiri::HTML(page_source)
    puts "parse the page content"
    # Gimme the first <img> tag
    image_from_the_page = page_content.css("img").select.first
    puts "got image from page"
    unless image_from_the_page
      return
    end

    # From that img tag, gimme the src attribute
    src_attribute = image_from_the_page.attribute("src")
    puts "got src of img"
    unless src_attribute
      return
    end

    # Download that image content and put it in the image
    @story.image = open(src_attribute.value)
    @story.save
    puts "downladed image."
  rescue MiniMagick::Error, Errno::ENOENT
    puts "Not gonna process this image"
  end
end

app/models/story.rb
class Story < ApplicationRecord
  validates :link, presence: true
  validates :link, format: { with: /\A(http|https)/ }

  belongs_to :created_by, class_name: "User"
  has_many :comments

  include ImageUploader[:image]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def authorize!
    redirect_to login_path unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.create(comment_params)
    @comment.created_by = current_user
    @comment.save
    redirect_to story_path(@story)

  end

private
  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]

    user = User.find_by(email: email)

    if user && user.authenticate(password)
      session[:user_id] = user.id

      redirect_to stories_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to stories_path
  end
end

app/controllers/stories_controller.rb
require 'nokogiri'
require 'open-uri'

class StoriesController < ApplicationController
  # GET /stories
  before_action :authorize!, except: [:index]
  def index
    @page = params[:page].to_i
    @starting_number = @page == 0 ? 0 : (@page - 1) * 20

    @stories = Story.all.order(created_at: :desc).page(@page).per(20)
  end

  # GET /stories/1
  def show
    @story = Story.find(params[:id])
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])

    unless @story.created_by == current_user
      redirect_to stories_path, notice: "You have to have written this article"
      return
    end
  end

  # POST /stories
  def create
    @story = Story.new(story_params)
    @story.created_by = current_user

   # THINGS THAT MODIFY @STORY GO HERE
   grabber = LinkImageGrabber.new(@story)
   grabber.process

    if @story.save
      redirect_to stories_path, notice: 'Story was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stories/1
  def update
    @story = Story.find(params[:id])

    unless @story.created_by == current_user
      redirect_to stories_path, notice: "You have to have written this article"
      return
    end

    if @story.update(story_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stories/1
  def destroy
    @story = Story.find(params[:id])

    unless @story.created_by == current_user
      redirect_to stories_path, notice: "You have to have written this article"
      return
    end

    @story.destroy
    redirect_to stories_url, notice: 'Story was successfully destroyed.'
  end

  private
  # Only allow a trusted parameter "white list" through.
  def story_params
    params.require(:story).permit(:title, :link, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to stories_path
    else
      redirect_to signup_path
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.created_by.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@story, @story.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#", class: "navbar-brand" do %>
          Hacker
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", stories_path %></li>
          <li class="active"><%= link_to "New", new_story_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          <li>
            <p class="navbar-text">Logged in as: <%= current_user.name %></p>
          </li>
          <li>
            <%= link_to "Logout", logout_path %>
          </li>
          <% else %>
          <li>
            <%= link_to 'Login', login_path %>
          </li>
          <li>
            <%= link_to 'Signup', signup_path %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @story.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h4>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
          <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
  </div>
  <div class="form-group">
          <%= f.label :link, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :link, class: "form-control" %>
      </div>
  </div>
  <div>
    <%= f.hidden_field :image, value: @story.cached_image_data %>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end -%>

app/views/stories/edit.html.erb
<div class="page-header">
  <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @story, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing story</h1>
</div>

<%= render 'form' %>

app/views/stories/index.html.erb
<div class="page-header">
  <%= link_to new_story_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Story
  <% end %>
  <h1 Listing>stories</h1>
</div>
<%= paginate @stories %>
<ul class="list-group">
  <% @stories.each.with_index do |story, index| %>
    <li class="list-group-item story-item">
      <div class="media">
        <div class="pull-left">
          <%= index + 1 + @starting_number %>
        </div>
        <div class="pull-right">
          <%= link_to story do %>
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
          <%= link_to edit_story_path(story) do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
          <%= link_to story, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </div>
        <% if story.image_url(:thumbnail) %>
        <div class="media-left">
          <%= image_tag(       story.image_url(:thumbnail), size: "64x64"      ) %>
        </div>
        <%else %>
        <div class="media-left">
          <img class="media-object" src="/images/twothumbsup.jpg" width="64" height="64">
        </div>
        <% end %>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to story.title, story.link %></h4>
          <span>created by <%= story.created_by.email %></span><span> <%= distance_of_time_in_words(Time.now.to_i - story.created_at.to_i) %></span> ago
        </div>

      </div>
    </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<div class="page-header">
  <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New story</h1>
</div>

<%= render 'form' %>

app/views/stories/show.html.erb
<div class="page-header">
  <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_story_path(@story), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show story</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @story.title %></dd>

  <dt>Link:</dt>
  <dd><%= @story.link %></dd>

  <dt>Email:</dt>
  <dd><%= @story.created_by.email %></dd>
</dl>
<div>
  <%= image_tag @story.image_url(:medium) %>
</div>

<h2>Comments</h2>
<%= render @story.comments %>
<%= render 'comments/form' %>

app/views/users/new.html.erb
<div class="page-header">
       <h1>Signup!</h1>
     </div>

     <%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
       <div class="form-group">
         <%= f.label :name, class: "col-sm-2 control-label" %>
         <div class="col-sm-10">
           <%= f.text_field :name, class: "form-control" %>
         </div>
       </div>
       <div class="form-group">
         <%= f.label :email, class: "col-sm-2 control-label" %>
         <div class="col-sm-10">
           <%= f.text_field :email, class: "form-control" %>
         </div>
       </div>
       <div class="form-group">
         <%= f.label :password, class: "col-sm-2 control-label" %>
         <div class="col-sm-10">
           <%= f.password_field :password, class: "form-control" %>
         </div>
       </div>
       <div class="form-group">
         <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
         <div class="col-sm-10">
           <%= f.password_field :password_confirmation, class: "form-control" %>
         </div>
       </div>
       <%= f.submit "Submit", class: "btn btn-primary" %>
     <% end %>